//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LE_Builder_Sharp.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LE_Builder_Sharp.i18n.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_dit Project.
        /// </summary>
        public static string MI_General_EditProject_Header {
            get {
                return ResourceManager.GetString("MI_General_EditProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MI_General_Exit {
            get {
                return ResourceManager.GetString("MI_General_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export project _to XML.
        /// </summary>
        public static string MI_General_ExportToXml_Header {
            get {
                return ResourceManager.GetString("MI_General_ExportToXml_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _General.
        /// </summary>
        public static string MI_General_Header {
            get {
                return ResourceManager.GetString("MI_General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import project _from XML.
        /// </summary>
        public static string MI_General_ImportFromXml {
            get {
                return ResourceManager.GetString("MI_General_ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Project.
        /// </summary>
        public static string MI_General_NewProject_Header {
            get {
                return ResourceManager.GetString("MI_General_NewProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project _List.
        /// </summary>
        public static string MI_General_ProjectList_Header {
            get {
                return ResourceManager.GetString("MI_General_ProjectList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MI_General_Settings_Header {
            get {
                return ResourceManager.GetString("MI_General_Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE Builder Sharp.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
